package com.example.testapplication.entity.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig httpCacheDaoConfig;

    private final HttpCacheDao httpCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        httpCacheDaoConfig = daoConfigMap.get(HttpCacheDao.class).clone();
        httpCacheDaoConfig.initIdentityScope(type);

        httpCacheDao = new HttpCacheDao(httpCacheDaoConfig, this);

        registerDao(HttpCache.class, httpCacheDao);
    }
    
    public void clear() {
        httpCacheDaoConfig.clearIdentityScope();
    }

    public HttpCacheDao getHttpCacheDao() {
        return httpCacheDao;
    }

}
